### ISSUE TITLE
Fail strategy for all BatchClients

### ISSUE THREAD

**Issue by joelwurtz** [php-http/client-common#10]
The principle would be to add a strategy on how a batch client should fail or not when sending multiple requests.

The default strategy would be the actual one, if one request fail a Exception is thrown.

Other strategy that can be done
- Majority (Quorum ?): if <=50% of requests failed then it will throw an exception
- All: Throw an exception only if all requests have failed

**Comment by sagikazarmark** [comment]
Not sure about this. If every request is meaningful, then it would make sense to fail even if one of them failed.

**Comment by dbu** [comment]
as you need exception handling even if you only get an exception if all requests fail, i think this is complicating too much. if somebody really needs some custom logic, they can try-catch and decide based on the exception if they need to abort or can ignore the exception because there was enough success, whatever their definition of success is.

so -1 on adding this.

**Comment by dbu** [comment]
okay if we close this?
