### ISSUE TITLE
HttpClientRouter

### ISSUE THREAD

**Issue by joelwurtz** [php-http/client-common#12]
A client accepting a map of regex -> httpclient. Given a specific request, it will check the uri of it and redirect to a specific http client implementation.

This allow to have a single pipeline for multiple library, but still allows using different client for some requests.

**Comment by sagikazarmark** [comment]
I think this came up as an idea back then when we removed options from clients and requests. I like the idea, although it might be a bit hard to configure.

Instead of regex, I could imagine something like the Matching authentication strategy, where the match is decided based on a callback, which in turn could be a regex check.

**Comment by joelwurtz** [comment]
Callback is better yes, so we can match against a specific header and not only the url. We can maybe reuse the idea of the RequestMatcher of Symfony (but need to be reimplemented as it's not on PSR7)

BTW should this request matcher be on php-http/message ? (Would introduce a new dependency here)

**Comment by sagikazarmark** [comment]
Not sure what that request matcher do, will take a look at it.

**Comment by joelwurtz** [comment]
Pretty simple :) https://github.com/symfony/http-foundation/blob/master/RequestMatcherInterface.php

**Comment by sagikazarmark** [comment]
Hm, yeah, I think this should go into the message package, but I don't think we need to add it as a dependency here. We only need it as a typehint, which allows us to make it an optional dependency.
