### ISSUE TITLE
Make clients final

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/client-common#20]
| Q | A |
| --- | --- |
| Bug? | no |
| New Feature? | yes |
| Version | 2.0.0 |

Make the rest of clients final. See #18 and #19

- [x] `BatchClient`
- [x] `BatchResult`
- [x] `Deferred`
- [x] `LeastUsedClientPool`
- [x] `RoundRobinClientPool`
- [x] `HttpMethodsClient`
- [x] `PluginClient`
- [x] `PluginClientFactory`
- [x] All Plugins

**Comment by dbu** [comment]
updated description, i think we should also make all other classes that are not meant to be extended final.

**Comment by Jean85** [comment]
I was trying to address this issue, but making the last non-final plugin final (RedirectPlugin) is pretty hard, since the class is extended in the specs to create stubs. This is obviously wrong because it tries to test internal behavior, but I'm not be able to solve that easily. Anyone else up for this?

**Comment by dbu** [comment]
there is https://github.com/php-http/client-common/milestone/3 - imho we should use the milestone to group all tasks for the 2.0 release.

**Comment by dbu** [comment]
i guess thats why its not yet final :-/
can you do a pull request with all that works, and a note that the RedirectPlugin is missing? maybe mark can see if he finds a better way for the testing of that plugin?

**Comment by sagikazarmark** [comment]
Yup, will take a look at it: #21

**Comment by dbu** [comment]
i think we now made final everything that can be final
