### ISSUE TITLE
Change plugin settings

### ISSUE THREAD

**Issue by hpatoio** [php-http/client-common#21]
I know this is not the best place to ask for support but I couldn't find a better one. 

I've create a library using `php-http` you can see a draft here https://github.com/hpatoio/lotadata/ 
I use `PluginClient` and as suggested in the [doc](http://docs.php-http.org/en/latest/plugins/introduction.html#libraries-that-require-plugins) I've created a [factory](https://github.com/hpatoio/lotadata/blob/master/src/HttpClientFactory.php) that create the http client that I then pass to the library.

Everything works and I can use it like this:

```
<?php

include_once('vendor/autoload.php');

use Hpatoio\Lotadata\HttpClientFactory;

$lotadataApiClient = new Hpatoio\Lotadata\LotadataClient(
    HttpClientFactory::create('here_my_api_key')
);

$categories = $lotadataApiClient->getTaxonomy("EventCategory");

foreach ($categories as $category) {
        echo "CATEGORY ".$category['name']."\n";
}
```

In the doc [doc](http://docs.php-http.org/en/latest/plugins/introduction.html#libraries-that-require-plugins) you say

> this allows [..] to inject their own plugins or configure a different client.

but I don't understand how you can inject a plugin. 

For instance in the code above : 
- how do you inject the `Cache Plugin` ?
- how do you change the setting for a plugin ? Let's say you want to change log level ?

Thanks.

**Comment by dbu** [comment]
i think the idea of that paragraph was that the users can chose to not use the factory but instead instantiate their own thing. the userland code could look like this:

```
$client = HttpClientDiscovery::find();
$client = new PluginClient($client, [
    new CachePlugin(my config),
    new LoggerPlugin(my config),
]);
$client = HttpClientFactory::create($user, $pass, $client);
```

your question reveils that the section is a bit vague however, we should improve it.

another example we could provide would be to have an array of options that you can pass to your factory method. something like

```
$options = [
    'auth_plugin' => ...
    'extra_plugins' => ...
];
```

and the factory would add its own required plugins if one is not specified, and then merge with the extra plugins. that would avoid having 2 nested plugin clients.

@sagikazarmark wdyt?

**Comment by sagikazarmark** [comment]
Configuration is one of the most difficult topics in HTTPlug IMO. In the past (and unfortunately it is still a common practice) we had `setConfig` and other similar methods. In HTTPlug this is strictly forbidden as we provide a very common abstraction which allows high level interoperability. This means that every configuration must happen at instantiation time, since we don't provide anything as part of the abstraction (thank god).

Since it is not part of the abstraction, this is something that can hardly be done with reuse in mind (defensive programming: code for your use case).

One thing we do is providing package integration for frameworks (Symfony only at the moment). Frameworks are also mostly about configuring your application. However, we can only provide a few common configuration options, in advanced cases you still have to configure your own services, etc.

So back to the beginning: I do think we should provide a few tips for creating proper configuration, but we can't provide an ultimate way and solution as there is none.

**Comment by hpatoio** [comment]
Thanks @sagikazarmark and @dbu 

I knew that you didn't provide a `setConfig` method for a good reason and @sagikazarmark explained why.

BTW I think that my 2 needs are quite common for someone who create a library. 
So what's the best way to:

 - Add a plugin to a client ? For instance the Cache Plugin
 - Change the setting for a plugin ? Let's say you want to change log level

Thanks.

**Comment by sagikazarmark** [comment]
> Add a plugin to a client ? For instance the Cache Plugin

There are three ways I would try:

Create a client factory, which accepts a specific structure of configuration. Like an array with the keys as plugin names and values are other arrays with plugin specific configuration in them. You still have to write the handling logic (if there is a key cache, then create a cache plugin and pass the config), but allows you two things:

- reuse your factory
- expand it with new plugins

You don't have to limit the configuration to plugins, you can include client config as well.

The other way is to manually configure the client and put it in a DiC. Based on your application level (plain PHP, (micro-)framework) this can be simple or ugly. I would say you should only do this if you need a quick solution in a micro-framework or something.

The third way is configuring a DiC based on its capabilities. This might not differ from the previous solution at all, but in case of symfony, you have a nice service configuration.

> Change the setting for a plugin ? Let's say you want to change log level

Change? When? If you want to make it configurable, I think the above listed things are your best options.

Runtime modification is not really a good idea. Mostly because it makes the abstraction much more heavier, partly because it is harder to rely on your code, if you can randomly change configuration runtime.

You might be able to get the same logger service from a DiC and modify it's logger level directly (level is only a question when you configure handlers, not one in case of a log message producer), but that sounds hackish.

Adding the library context to these questions: I am not really sure that you should care about configuration.

Let's take an API client example: what configurations do you NEED (details which is required to make it work)?

- If you have multiple endpoints, a base URL
- Some authentication

These are the details what you need to make it work. But even these can be subject of HTTP Client configuration. With other words: you can make this responsibility of the library consumer. Why is this good?

Because you give freedom. The library consumer can write a custom HTTP Client or just a wrapper which includes this information. Or can use a plugin. Even then, the consumer might not want to include these details in a log, so he/she can play with the order of plugins.

Logging and caching are also responsibilities of the library user. IMO it is not so common that you need to cache an API call. You might need to, when you receive large amount of data which rarely change. Logging is also something that depends on the application where you use the library. In a million daily views application you might want to use logging.

Of course you can provide a quick setup client factory which does all these configurations for the user. It's simple. For this case see the solutions above. But what's really great about the whole thing is your library's user should be able to have complete control over the configuration which allows flexibility.

**Comment by sagikazarmark** [comment]
Did we answer your question @hpatoio ? Can we close this issue?
