### ISSUE TITLE
[RFC] QueryDefaultPlugin

### ISSUE THREAD

**Issue by Nyholm** [php-http/client-common#66]
I talk to an API where I identify myself with query parameters. (yes, that is wrong but I cannot change this.) I see a value in having a plugin much like `DefaultHeaderPlugin` but for URI queries.

**Comment by dbu** [comment]
while thats a bit odd i don't think its very wrong to have such a plugin.

for your use case, would that not rather be a new implementation of
https://github.com/php-http/message/blob/master/src/Authentication.php ?
that way the credentials can be handled more dynamically if needed.

**Comment by sagikazarmark** [comment]
We had such Authentication method in the past and we decided to remove it, because it's wrong. I would be more comfortable with a generic purposes query plugin, which does not suggest any weird usage. Or you can just implement an Authentication method for the project, if the API developers change this behaviour, you can easily exchange the credentials, but I'm not a huge fan of adding that auth method back

**Comment by Nyholm** [comment]
A better use case could be when you are an `locale` parameter in the URL. 

I will submit a PR or a QueryDefaultPlugin
